Allow ResolverTypeWrapper to return null or Promise<null>
In the linked blog post for the typescript-resolvers plugin
there is a TS error (TS2322) because the users query could
find no matching user and therefore return undefined:

```
src/resolvers.ts:16:5 - error TS2322: Type '(parent: {}, args: RequireFields<QueryUserArgs, "id">) => { id: string; email: string; profile: { age: number; name: string; }; } | undefined' is not assignable to type 'Resolver<ResolverTypeWrapper<User>, {}, any, RequireFields<QueryUserArgs, "id">> | undefined'.
  Type '(parent: {}, args: RequireFields<QueryUserArgs, "id">) => { id: string; email: string; profile: { age: number; name: string; }; } | undefined' is not assignable to type 'ResolverFn<ResolverTypeWrapper<User>, {}, any, RequireFields<QueryUserArgs, "id">>'.
    Type '{ id: string; email: string; profile: { age: number; name: string; }; } | undefined' is not assignable to type 'ResolverTypeWrapper<User> | Promise<ResolverTypeWrapper<User>>'.
      Type 'undefined' is not assignable to type 'ResolverTypeWrapper<User> | Promise<ResolverTypeWrapper<User>>'.

16     user: (parent, args) => {
       ~~~~

Found 1 error.
```

I think there is a legitimate case where this would fail
and we'd want to return null or potentially Promise<null>
with `Promise<T | null> | T | null`.

Blog post is here: https://the-guild.dev/blog/better-type-safety-for-resolvers-with-graphql-codegen